# Generated by Django 5.1 on 2024-08-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to='avatars/')),
            ],
        ),
    ]
