# Generated by Django 5.1 on 2024-09-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_management', '0008_alter_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='MatchHistory',
        ),
    ]
