# Generated by Django 5.1 on 2024-09-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
