# Generated by Django 5.1 on 2024-09-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_remove_match_player1_remove_match_player2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='display_name',
        ),
    ]
