# Generated by Django 5.1 on 2024-09-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_remove_customuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='Anonymous', max_length=100, unique=True),
        ),
    ]
