# Generated by Django 5.1 on 2024-10-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_customuser_friends_customuser_last_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='energie_point',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skill_point',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
