services:
  database:
      image:  postgres:latest
      container_name: database
      ports:
        - "5432:5432"
      networks:
        - mynetwork
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: mypassword
        POSTGRES_DB: postgres
      volumes:
        - pgdata:/var/lib/postgresql/data
  web:
    container_name: django
    build: .
    command: >
      sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - database

volumes:
  pgdata: 
networks: 
  mynetwork: 
    name: mynetwork